#Config
#Version later to be used to maintain config
version: 1.0.0

#How long to wait for players to join in seconds
waitingDelay: 20

#Mob delay, interval to spawn mobs near players
mobDelay: 7

#Time in seconds to protect the player on spawn
#Set to 0 to have no protection time
noDamageDelay: 10

#Minimum amount of players needed to join
minimumPlayers: 2

#The game mode type for the arena
#Values: "collectItems", "findBlock"
mode: "collectItems"

#Item to collect to win the maze, (must get to exit with the item)
#The item name is from the Material type list in Bukkit
###Used in mode "collectItems" only###
itemToCollect: GOLD_NUGGET

#The amount of the item above to collect
###Used in mode "collectItems" only###
itemAmountToCollect: 10

#The block you must find
###Used in mode "findBlock" only###
blockMaterial: GOLD_BLOCK

#Allow joining even when a game is in progress
joinWhenever: true

#Random spawn
randomSpawn: true

#Allow pvp in arena
#To allow pvp you must also enable in server.properties
allowPvP: true

